set -g mouse on
set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g allow-passthrough on
set -s set-clipboard on
set -as terminal-features ',xterm-256color:clipboard'
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
